# Generated by Django 2.1.5 on 2020-02-29 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
                ('resume_date', models.DateField()),
                ('employee', models.CharField(max_length=200)),
                ('home_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='applyleave',
            name='leave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='leave.Leave'),
        ),
        migrations.AddField(
            model_name='applyleave',
            name='person_taking_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_taking', to='accounts.Employee'),
        ),
    ]
