# Generated by Django 2.1.5 on 2020-02-29 21:26

import Legal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('dated', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('dofsigning', models.DateField(default=datetime.datetime.now)),
                ('doflapsing', models.DateField(default=datetime.datetime.now)),
                ('document', models.FileField(upload_to=Legal.models.UploadFolder('documents/legal'))),
                ('description', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Legal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='GS1Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('dated', models.DateField(default=datetime.datetime.now)),
                ('document', models.FileField(upload_to=Legal.models.UploadFolder('documents/legal'))),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('dated', models.DateField(default=datetime.datetime.now)),
                ('document', models.FileField(upload_to=Legal.models.UploadFolder('documents/legal'))),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
