# Generated by Django 2.1.5 on 2020-03-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20200302_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Date_naissance',
        ),
    ]
