# Generated by Django 2.1.5 on 2020-03-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_remove_client_date_naissance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
    ]
