# Generated by Django 2.1.5 on 2020-03-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20200302_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
