# Generated by Django 2.1.5 on 2020-02-29 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('initials', models.CharField(max_length=20)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('initials', models.CharField(max_length=20)),
                ('department', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='departments.Department')),
            ],
        ),
    ]
